### ISSUE TITLE
Practica de Operaciones con Conjunto

### ISSUE THREAD

**Issue by NBbrook** [SistemasTecTlaxiaco/actividad-5-practica-de-conjuntos-club-noobbaby#1]
[Practicas de Equipo.pdf](https://github.com/SistemasTecTlaxiaco/actividad-5-practica-de-conjuntos-club-noobbaby/files/12755084/Practicas.de.Equipo.pdf)

**Comment by elisa1223** [comment]
Portada 25%
Procedimiento 22%
Figuras e ilustraciones y fotografías 22%
Resultados y conclusiones 22.5%

Calificacion final:  18.3 / 20
Evaluado por el equipo de Elisa Sánchez Coronel.

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
